package com.moments.android.views.messaging.groups

import com.moments.android.R

internal fun groupStringId(key: String): Int = when (key) {
    "title" -> R.string.groups_title
    "empty" -> R.string.groups_empty
    "emptyBody" -> R.string.groups_empty_body
    "memberCount" -> R.string.groups_member_count
    "create" -> R.string.groups_create
    "name" -> R.string.groups_name
    "pickerHint" -> R.string.groups_picker_hint
    "selectedCount" -> R.string.groups_selected_count
    "noConnections" -> R.string.groups_no_connections
    "add" -> R.string.groups_add
    "search" -> R.string.groups_search
    "details" -> R.string.groups_details
    "privacy" -> R.string.groups_privacy
    "older" -> R.string.groups_older
    "reply" -> R.string.groups_reply
    "photo" -> R.string.groups_photo
    "message" -> R.string.groups_message
    "cancel" -> R.string.groups_cancel
    "send" -> R.string.groups_send
    "save" -> R.string.groups_save
    "mute" -> R.string.groups_mute
    "members" -> R.string.groups_members
    "owner" -> R.string.groups_owner
    "admin" -> R.string.groups_admin
    "promote" -> R.string.groups_promote
    "demote" -> R.string.groups_demote
    "remove" -> R.string.groups_remove
    "manage" -> R.string.groups_manage
    "leave" -> R.string.groups_leave
    "leaveBody" -> R.string.groups_leave_body
    "removeBody" -> R.string.groups_remove_body
    "errorTitle" -> R.string.groups_error_title
    "ok" -> R.string.groups_ok
    "back" -> R.string.groups_back
    "error" -> R.string.groups_error
    "unavailable" -> R.string.groups_unavailable
    "keyError" -> R.string.groups_key_error
    "sendError" -> R.string.groups_send_error
    "photoError" -> R.string.groups_photo_error
    "manageError" -> R.string.groups_manage_error
    "notification" -> R.string.groups_notification
    "invitations" -> R.string.groups_invitations
    "accept" -> R.string.groups_accept
    "decline" -> R.string.groups_decline
    "invited" -> R.string.groups_invited
    "invitedYou" -> R.string.groups_invited_you
    "pendingInvitations" -> R.string.groups_pending_invitations
    "inviteForbidden" -> R.string.groups_invite_forbidden
    "inviteForbiddenOne" -> R.string.groups_invite_forbidden_one
    "inviteForbiddenMany" -> R.string.groups_invite_forbidden_many
    "inviteLink" -> R.string.groups_invite_link
    "invitation" -> R.string.groups_invitation
    "joinBody" -> R.string.groups_join_body
    "linkBody" -> R.string.groups_link_body
    "getLink" -> R.string.groups_get_link
    "shareLink" -> R.string.groups_share_link
    "renewLink" -> R.string.groups_renew_link
    "disableLink" -> R.string.groups_disable_link
    "edit" -> R.string.groups_edit
    "copyLink" -> R.string.groups_copy_link
    "linkCopied" -> R.string.groups_link_copied
    "renewBody" -> R.string.groups_renew_body
    "disableBody" -> R.string.groups_disable_body
    "joinLink" -> R.string.groups_join_link
    "linkError" -> R.string.groups_link_error
    "notice.joined" -> R.string.groups_notice_joined
    "notice.left" -> R.string.groups_notice_left
    "notice.removed" -> R.string.groups_notice_removed
    "intro.createdBy" -> R.string.groups_intro_created_by
    "intro.createdOn" -> R.string.groups_intro_created_on
    "intro.encrypted" -> R.string.groups_intro_encrypted
    "historyStart" -> R.string.groups_history_start
    "historyStartJoined" -> R.string.groups_history_start_joined
    "you" -> R.string.groups_you
    "followingSection" -> R.string.groups_following_section
    "othersSection" -> R.string.groups_others_section
    "linkAdminOnly" -> R.string.groups_link_admin_only
    "typing.one" -> R.string.groups_typing_one
    "typing.two" -> R.string.groups_typing_two
    "typing.several" -> R.string.groups_typing_several
    "searchMembers" -> R.string.groups_search_members
    "noMembersFound" -> R.string.groups_no_members_found
    "mention.placeholder" -> R.string.groups_mention_placeholder
    "notification.mention" -> R.string.groups_notification_mention
    "description" -> R.string.groups_description
    "descriptionPlaceholder" -> R.string.groups_description_placeholder
    "send.everyone" -> R.string.groups_send_everyone
    "send.admins" -> R.string.groups_send_admins
    "send.locked" -> R.string.groups_send_locked
    "dissolve" -> R.string.groups_dissolve
    "dissolveBody" -> R.string.groups_dissolve_body
    "notice.dissolved" -> R.string.groups_notice_dissolved
    "mute.8h" -> R.string.groups_mute_8h
    "mute.week" -> R.string.groups_mute_week
    "mute.always" -> R.string.groups_mute_always
    "link.approval" -> R.string.groups_link_approval
    "join.requested" -> R.string.groups_join_requested
    "joinRequests" -> R.string.groups_join_requests
    "approveJoin" -> R.string.groups_approve_join
    "report" -> R.string.groups_report
    "report.subtitle" -> R.string.groups_report_subtitle
    else -> R.string.groups_error
}
